services:
   redis: 
     image: redis
     container_name: redis
     ports:
       - '6379:6379'

   streamlit:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'